set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

call plug#begin('$XDG_DATA_HOME/vim/plugged')
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'enricobacis/vim-airline-clock'
  Plug 'scrooloose/nerdtree'
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim'
  Plug 'suan/vim-instant-markdown', {'for': 'markdown'}
  Plug 'ycm-core/YouCompleteMe'
  Plug 'xuyuanp/nerdtree-git-plugin'
  Plug 'tpope/vim-fugitive'
  Plug 'mhinz/vim-signify'
call plug#end()

source ~/.config/vim/nerdtree.vim
source ~/.config/vim/fzf.vim
source ~/.config/vim/ycm.vim
source ~/.config/vim/signify.vim

set number relativenumber

map <SPACE> <leader>
